In [1]:
import pandas as pd
import os
from scipy import stats  
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data = pd.read_csv('project_data/full_dataset.csv')
data

/var/folders/7d/2d_kq54s00v0272gkndgzxd80000gn/T/ipykernel_22913/726512130.py:1: DtypeWarning: Columns (27,28,29,33,34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('project_data/full_dataset.csv')

,tweet_id,user_id,created_at,ANEW_Valence,ANEW_Dominance,ANEW_Arousal,Happiness,NRC_anger,NRC_anticipation,NRC_disgust,...,comorbid,cohort,inferred_timezone,timezone_loss,day_of_week,female_prop,gender,VADER_NEG,VADER_NEU,VADER_POS
0,tD2616237,uANX100,2020-04-30 14:43:57+00:00,3.352500,5.570000,4.537500,4.501818,0.0,0.0,2.0,...,True,other,-7,0.007052,3,0.954,female,0.000,0.761,0.239
1,tD2616238,uANX100,2020-04-29 19:58:40+00:00,3.220000,2.560000,5.450000,4.260000,0.0,0.0,0.0,...,True,other,-7,0.007052,2,0.954,female,0.304,0.617,0.079
2,tD2616239,uANX100,2020-04-29 19:56:33+00:00,5.681667,5.098333,3.965000,5.322105,0.0,1.0,0.0,...,True,other,-7,0.007052,2,0.954,female,0.000,1.000,0.000
3,tD2616240,uANX100,2020-04-29 00:46:02+00:00,3.850000,5.170000,4.670000,5.380000,0.0,0.0,0.0,...,True,other,-7,0.007052,2,0.954,female,0.000,1.000,0.000
4,tD2616241,uANX100,2020-04-28 05:48:45+00:00,6.100000,5.930000,4.246667,5.514091,0.0,0.0,0.0,...,True,other,-7,0.007052,1,0.954,female,0.000,0.860,0.140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2104133,tD0139188,uPDD001,2019-07-27 09:19:28+00:00,6.500000,6.310000,3.140000,5.493333,0.0,0.0,0.0,...,True,other,-8,0.021424,5,0.744,female,0.086,0.795,0.119
2104134,tD0139189,uPDD001,2019-07-27 09:19:05+00:00,NaN,NaN,NaN,NaN,0.0,0.0,0.0,...,True,other,-8,0.021424,5,0.744,female,0.000,0.714,0.286
2104135,tD0139190,uPDD001,2019-07-27 09:16:25+00:00,5.780000,4.670000,3.710000,5.252000,0.0,0.0,0.0,...,True,other,-8,0.021424,5,0.744,female,0.000,0.572,0.428
2104136,tD0139191,uPDD001,2019-07-27 09:16:15+00:00,NaN,NaN,NaN,6.090000,0.0,0.0,0.0,...,True,other,-8,0.021424,5,0.744,female,0.000,0.747,0.253
2104137,tD0139192,uPDD001,2019-07-27 09:15:14+00:00,5.943333,5.043333,3.413333,5.118333,0.0,0.0,0.0,...,True,other,-8,0.021424,5,0.744,female,0.252,0.662,0.086

In [3]:
data['gender_female'] = data['gender'].map(lambda x: 1 if x == 'female' else 0)

data.groupby('user_id').agg({
    'tweet_id' : 'count',
    'group_anxiety' : 'min',
    "gender_female" : "first",
    'group_depression' : 'min','19-29' : 'mean',
        '30-39' : 'mean',
        '<=18' : 'mean',
        '>=40' : 'mean',}).reset_index().groupby('group_anxiety').agg({
        'user_id' : 'nunique',
        'tweet_id' : ['mean', 'std'],
        'gender_female':'sum',
        '19-29' : 'mean',
        '30-39' : 'mean',
        '<=18' : 'mean',
        '>=40' : 'mean',
    })

              user_id     tweet_id             gender_female     19-29  \
              nunique         mean         std           sum      mean
group_anxiety
False            1270  1182.737795  991.613431           717  0.406208
True              492  1169.928862  888.670868           293  0.418078

                  30-39      <=18      >=40
                   mean      mean      mean
group_anxiety
False          0.153847  0.334648  0.105299
True           0.188736  0.306703  0.086484